!## Talant Ruzmetov 08/10/2017
!## This code calculates all non native intermolecular contacts between 2 units.
!## It uses native info generated by Cafemol to get native pairwise contact list, then based on that
!## list generates non-native contact indecies.

program NonNatContactCalculation 
  implicit none
  integer,parameter:: nmax = 200
  real:: x, y, z, dx, dy, dz
  real:: q_non_nat, gen_dist_non_nat
  integer:: ii, jj, i1, count, k, ll, m
  integer:: tot_non_nat_contacts, tot_native_contacts, tot_contacts
  integer:: i, j, l, n, iframe, frame_n, N_beads, ires
  integer:: res_num1, res_num2, n_link, inon
 ! real,dimension(nmax)::dist_nat 
  character(LEN=72):: char72
  character(LEN=80):: char500
  character(LEN=4):: nameofatom
  character(LEN=3):: resname
  character(LEN=7)::nameid
  integer:: nca, icon, imp1, imp2, iunit1, iunit2, imp1un, imp2un
  real,dimension(nmax,3):: rca
  integer,dimension(3000,2):: u, u_non_nat, u_all, u_new
  real:: dist, d_cm, rcm, go_nat_dist
  character (LEN=3),dimension(nmax):: Lsequence
  character(LEN=32):: arg1

  
  !###############################-- some parameters--##############################################
  res_num1 = 81                 !|> number of residues for unit1 (KIX)
  res_num2 = 28                 !|> number of residues for unit2 (pKID)
  n_link = 2                    !|> num res for linker
  N_beads = res_num1 + res_num2 !|> Total number of residues 
  gen_dist_non_nat = 6.5        !|> generic non-native contact distance ??????????????????????????????????
  
!####################--argument passing from term--################################################
  do j = 1, iargc()
     call getarg(j, arg1)
     read(arg1,*) frame_n  !|> total number of frames for trajectory file
  enddo
  

!####################-- This loop reads native info file, stores contact indecies and calculates
  ll = 0
  open(unit=71,file = '1KDX.ninfo', status = 'unknown') 
  ninfo_lines:do
     read(71,'(a80)', END = 550) char500
     if(char500(1:7) /= 'contact') cycle ninfo_lines
     
     read(char500,'(a7,4x,i3,5x,i2,5x,i2,4x,i3,4x,i3,5x,i2,5x,i2,5x,f10.5)') nameid,icon,iunit1, &
          iunit2,imp1,imp2,imp1un,imp2un,go_nat_dist
     ll = ll + 1   !# this contact indecies are different(continuous) than "icon" 
     u(ll,1) = imp1
     u(ll,2) = imp2
  end do ninfo_lines
  
550 continue

  tot_native_contacts = ll

!##################################################################################################  
!#######################-- generating all intermolecular contact indecies--########################
  l = 0
  do i = 1, res_num1
     do j = res_num1 + 1, N_beads
        l = l + 1
        u_all(l,1) = i
        u_all(l,2) = j
     enddo
  enddo
  tot_contacts = l

  
!#######################-- sorting out non-nat from native contacts--###############################  ????????????
   do m = 1, tot_contacts
      do k = 1, tot_native_contacts
            
         if(u(k,1).ne.u_all(m,1).and.u(k,2).ne.u_all(m,2)) then
            u_non_nat(m,1) = u_all(m,1)
            u_non_nat(m,2) = u_all(m,2)
         else
            u_non_nat(m,1) = 0
            u_non_nat(m,2) = 0
         endif

      enddo
  enddo

  inon = 0
  do m = 1, tot_contacts
     if(u_non_nat(m,1).ne.0) then
        inon = inon + 1
        u_new(inon,1) = u_non_nat(m,1)
        u_new(inon,2) = u_non_nat(m,2)
     endif
  enddo
   
  tot_non_nat_contacts = inon  !|> number of intermolecular non native contacts 
!#########################################################################################################


  
  
!########################-- looping over movie frames to read coordinates--########################3  
  do iframe = 1, frame_n
     ires = 0
     Lines: do
        read(5,'(a72)',end=999) char72
        if(char72(1:3)=='END')then 
           exit Lines
        endif
        
        if(char72(1:4) /= 'ATOM') cycle Lines
        read(char72,1000) nameofatom,resname,x,y,z
        if(nameofatom .eq. ' CA ') then
           ires = ires + 1
           rca(ires,1) = x
           rca(ires,2) = y
           rca(ires,3) = z
           Lsequence(ires) = resname
        endif
1000    format(12x,a4,1x,a3,10x,3f8.3)
     end do Lines

     
     count = 0
     do i1 = 1, tot_non_nat_contacts
        ii = u_new(i1,1)
        jj = u_new(i1,2)
        dx = rca(ii,1) - rca(jj,1)
        dy = rca(ii,2) - rca(jj,2)
        dz = rca(ii,3) - rca(jj,3)
        
        dist = dx*dx + dy*dy + dz*dz
        dist = sqrt(dist)
        
        !# counting intermolecular contacts
        if(dist.le.1.200 * gen_dist_non_nat) then
           count = count + 1                  
        endif
                
     end do
     q_non_nat = count / real(tot_non_nat_contacts)
        

     write(6,'(i4)') count 
     !write(6,'(i4,2x,f8.4)') count , q_non_nat
     !write(6,'(6f7.2)') d_cm, d_cm_a, d_cm_b, theta_a, theta_b 
  end do
999 continue 
end program NonNatContactCalculation
